# Generated by Django 5.0.1 on 2024-01-27 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_cover', models.ImageField(upload_to='media/')),
                ('image', models.ImageField(upload_to='media/')),
                ('views', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to='')),
                ('ratings', models.FloatField()),
                ('release_date', models.DateField()),
                ('genres', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('THRILLER', 'Thriller'), ('DRAMA', 'Drama'), ('ROMANCE', 'Romance'), ('SCIFI', 'Sci-Fi'), ('HORROR', 'Horror')], default='ACTION', max_length=25)),
            ],
        ),
    ]
