# Generated by Django 5.0.1 on 2024-02-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_options_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
