# Generated by Django 5.0.1 on 2024-02-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
